services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: travel_management_system_user
      POSTGRES_PASSWORD: OBhuatKhTjYBflBiofeXEif
      POSTGRES_DB: travel_management_system
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: # Define the named volume
